
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Feb 20 10:55:29 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 6;
  public static final int IDENT = 29;
  public static final int QUESTION = 25;
  public static final int PERCENT = 13;
  public static final int PLUS = 9;
  public static final int RBRACE = 24;
  public static final int RPAREN = 20;
  public static final int EQUAL = 14;
  public static final int SEMI = 17;
  public static final int RETURN = 26;
  public static final int MINUSMINUS = 16;
  public static final int LBRACE = 23;
  public static final int LBRACKET = 21;
  public static final int LPAREN = 19;
  public static final int COLON = 7;
  public static final int RBRACKET = 22;
  public static final int PROGRAM = 2;
  public static final int MULTIPLE = 11;
  public static final int COMMA = 18;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int DIVIDE = 12;
  public static final int CHARCONST = 30;
  public static final int PLUSPLUS = 15;
  public static final int MINUS = 10;
  public static final int CONST = 3;
  public static final int PRINT = 5;
  public static final int error = 1;
  public static final int NEW = 4;
  public static final int VOID = 8;
  public static final int BOOLCONST = 28;
}

